"""remove col

Revision ID: b4f72cfa4d2e
Revises: 39e8c42d77d8
Create Date: 2020-12-12 12:13:10.289367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f72cfa4d2e'
down_revision = '39e8c42d77d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_another', table_name='items')
    op.drop_column('items', 'another')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('another', sa.VARCHAR(), nullable=True))
    op.create_index('ix_items_another', 'items', ['another'], unique=False)
    # ### end Alembic commands ###
